version: '3'

services:
  serverless:
    image: serverless-vue-aws:latest
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /sls
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./serverless:/sls
